"""Export operations: DDL/SQL generation from entity definitions."""

from .project import _get_default_db, _uid


def _get_type_mapping(data, db_defkey):
    """Get data type mapping for the given database."""
    mappings = data.get("dataTypeMapping", {}).get("mappings", [])
    for m in mappings:
        if m.get("defKey"):
            return m
    return {}


def _resolve_field_type(field, domains, mapping, db):
    """Resolve a field's domain to actual database type."""
    domain_id = field.get("domain", "")
    field_type = field.get("type", "")

    # If field has a direct type set, use it
    if field_type:
        return field_type

    # Look up domain -> applyFor -> mapping[db]
    for d in domains:
        if d.get("id") == domain_id:
            apply_for = d.get("applyFor", "")
            if mapping and apply_for:
                return mapping.get(db, "") or mapping.get(db.upper(), "") or field_type
    return field_type


def generate_ddl(data, db_defkey=None, include_drop=False):
    """Generate CREATE TABLE DDL statements for all entities.

    Returns a list of DDL strings.
    """
    if not db_defkey:
        db_defkey = _get_default_db(data)

    mapping = _get_type_mapping(data, db_defkey)
    domains = data.get("domains", [])
    entities = data.get("entities", [])
    statements = []

    for entity in entities:
        table_name = entity.get("defKey", "")
        if not table_name:
            continue

        fields = entity.get("fields", [])
        if not fields:
            continue

        cols = []
        pks = []

        for f in fields:
            fdef = f.get("defKey", "")
            if not fdef:
                continue
            ftype = _resolve_field_type(f, domains, mapping, db_defkey)
            flen = f.get("len", "")
            fscale = f.get("scale", "")
            fcomment = f.get("comment", "")
            fnotnull = f.get("notNull", False)
            fauto = f.get("autoIncrement", False)
            fdefault = f.get("defaultValue", "")
            fpk = f.get("primaryKey", False)

            type_str = _format_type(ftype, flen, fscale, db_defkey)

            col_parts = [f'  "{fdef}" {type_str}']
            if fnotnull:
                col_parts.append("NOT NULL")
            if fauto:
                if "postgre" in (db_defkey or "").lower():
                    col_parts.append("GENERATED BY DEFAULT AS IDENTITY")
                else:
                    col_parts.append("AUTO_INCREMENT")
            if fdefault:
                col_parts.append(f"DEFAULT {fdefault}")
            if fcomment and db_defkey and "hive" not in db_defkey.lower():
                col_parts.append(f"COMMENT '{fcomment}'")
            cols.append(" ".join(col_parts))

            if fpk:
                pks.append(f'"{fdef}"')

        if pks:
            cols.append(f'  PRIMARY KEY ({", ".join(pks)})')

        comment = entity.get("comment", "")
        table_comment = f" COMMENT = '{comment}'" if comment and "hive" not in (db_defkey or "").lower() else ""

        ddl = ""
        if include_drop:
            ddl += f'DROP TABLE IF EXISTS "{table_name}";\n'
        ddl += f'CREATE TABLE "{table_name}" (\n' + ",\n".join(cols) + f'\n){table_comment};'

        statements.append(ddl)

    return statements


def generate_ddl_for_entity(data, entity_id, db_defkey=None, include_drop=False):
    """Generate DDL for a single entity."""
    from .entity import get_entity
    entity = get_entity(data, entity_id)
    if not entity:
        raise ValueError(f"Entity not found: {entity_id}")
    # Temporarily replace entities list with just this one
    saved = data.get("entities", [])
    data["entities"] = [entity]
    result = generate_ddl(data, db_defkey, include_drop)
    data["entities"] = saved
    return result


def _format_type(ftype, flen, fscale, db_defkey):
    """Format a type with length/scale for the target database."""
    db_lower = (db_defkey or "").lower()
    ftype_upper = (ftype or "").upper()

    if not ftype:
        return "TEXT"

    if ftype_upper in ("VARCHAR", "CHAR", "NVARCHAR", "NCHAR"):
        if flen:
            return f"{ftype_upper}({flen})"
        return f"{ftype_upper}(255)"

    if ftype_upper in ("DECIMAL", "NUMERIC"):
        if flen and fscale:
            return f"{ftype_upper}({flen},{fscale})"
        if flen:
            return f"{ftype_upper}({flen})"
        return f"{ftype_upper}(10,0)"

    if ftype_upper in ("INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT",
                       "FLOAT", "DOUBLE", "REAL", "BOOLEAN"):
        return ftype_upper

    return ftype_upper


def export_sql(data, output_path, db_defkey=None, include_drop=False):
    """Export all DDL to a SQL file."""
    statements = generate_ddl(data, db_defkey, include_drop)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n\n".join(statements))
        f.write("\n")
    return output_path
